'use client';
import type {ProductDetail} from '@/lib/api';
import {useLang,getCategoryLabel} from '@/lib/language';
import {marketReview} from '@/lib/malaysia';
import {merchantLink,recordShoppingEvent,words} from '@/lib/shopping';
import ShoppingImage from './ShoppingImage';
export default function CatSupplyDetail({product}:{product:ProductDetail}) {
  const {lang}=useLang();const w=(en:string,zh:string,bm:string)=>words(lang,en,zh,bm);const review=marketReview(product.id);
  const platform=review?.buy_url.includes('shopee')?'shopee':'lazada';
  const link=merchantLink(product,platform);
  const affiliate=!!link?.affiliate;
  return <article className="shop-supply-detail"><div className="shop-supply-photo"><ShoppingImage url={product.image_url} name={product.name_en}/></div><div><span className="shop-eyebrow">{getCategoryLabel(product.category,lang)} · {product.brand}</span><h1>{product.name_en}</h1><p>{product.specification}</p><p>{w('Selected for cats. Check the pack contents and current availability with the seller.','猫专用商品。购买前请核对包装内容和商家实时库存。','Dipilih untuk kucing. Semak kandungan pek dan stok semasa dengan penjual.')}</p>{review?.availability === 'out_of_stock_observed' ? <section className="shop-buying"><h2>{w('Temporarily unavailable','暂不可购买','Tidak tersedia buat masa ini')}</h2><p>{w('The linked seller listing showed this item out of stock when checked. It is hidden from the catalogue until stock is confirmed again.','最近查验时商家页面显示缺货；重新确认有货前，该商品不会出现在目录中。','Penyenaraian penjual menunjukkan stok habis semasa semakan. Produk disorok sehingga stok disahkan semula.')}</p><small>{w('Checked','查验日期','Disemak')} {review.checked_at}</small></section> : review && <section className="shop-buying"><h2>{w('Buying options','购买选项','Pilihan membeli')}</h2><strong>{review.merchant}</strong><p>{w('Check current price and choose an option on the platform.','到平台查看现价并选择商品选项。','Semak harga semasa dan pilih pilihan produk di platform.')}</p>{affiliate && link && <a className="shop-primary" href={link.url} target="_blank" rel="sponsored noopener noreferrer" onClick={() => recordShoppingEvent('affiliate_click',product.id,platform,link.kind)}>{platform === 'shopee'?'Shopee':'Lazada'} ↗</a>}<p className="shop-note">{w('Listing reviewed','商品资料查阅于','Penyenaraian disemak')} {review.checked_at} · {w('Delivery: confirm your Malaysian postcode.','配送范围请以马来西亚收货邮编核对。','Penghantaran: sahkan poskod Malaysia anda.')}</p><p className="shop-note">{affiliate ? w('MeowLah may earn a commission from qualifying purchases through this affiliate link.','通过此联盟链接完成符合条件的购买，MeowLah 可能获得佣金。','MeowLah mungkin menerima komisen bagi pembelian yang layak melalui pautan afiliasi ini.') : w('No affiliate buying link is available for this item yet.','此商品目前没有可用的联盟购买链接。','Pautan pembelian afiliasi belum tersedia untuk item ini.')}</p></section>}</div></article>;
}
